services:
  web:
    build: .

    ports:
      - '8000:8000'

    volumes:
      - ./data:/app/data

    env_file:
      - .env

  bot:
    build: .
    command: ['python', '-m', 'src.tg_bot.main_bot']

    env_file:
      - .env