apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: fastapi-with-bot
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: varenikvkusny/fastapi-with-bot:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEY

            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BOT_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: fastapi-with-bot
spec:
  selector:
    app: bot
  ports:
    - port: 8000
      targetPort: 8000
